const PLACEHOLDER_ROLES = {
  TAG_NAME: Symbol('TAG_NAME'),
  ATTRIBUTE_OR_ATTRIBUTE_NAME: Symbol('ATTRIBUTE_OR_ATTRIBUTE_NAME'),
  ATTRIBUTE_VALUE: Symbol('ATTRIBUTE_VALUE'),
  PART_OF_ATTRIBUTE_OR_VALUE: Symbol('PART_OF_ATTRIBUTE_OR_VALUE'),

  ATTRIBUTE: Symbol('ATTRIBUTE'),
  ATTRIBUTE_NAME: Symbol('ATTRIBUTE_NAME'),

  TAG: Symbol('TAG'),
};

export default PLACEHOLDER_ROLES;
